import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navigation/nav-bar";
import { Footer } from "@/components/navigation/footer";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${outfit.variable}  antialiased`}>
                <Navbar />
                {children}
                <Footer />
                <Toaster />
            </body>
        </html>
    );
}
